-- 코드를 입력하세요
WITH CLS_1 AS
(
SELECT COUNT(DISTINCT USER_ID) AS TOT_CNT
FROM USER_INFO
WHERE YEAR(JOINED) = 2021
)

SELECT  YEAR(sales_date) AS YEAR,
        MONTH(sales_date) AS MONTH,
        COUNT(DISTINCT CASE WHEN YEAR(BB.JOINED) = 2021 THEN AA.USER_ID END) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT CASE WHEN YEAR(BB.JOINED) = 2021 THEN AA.USER_ID END) 
         / (SELECT TOT_CNT FROM CLS_1),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AA
LEFT JOIN USER_INFO BB ON AA.USER_ID = BB.USER_ID
GROUP BY 1,2
ORDER BY YEAR(sales_date) ASC, MONTH(sales_date) ASC