-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID, F.FILE_NAME, F.FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE F 
JOIN USED_GOODS_BOARD B
ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(BOARD.VIEWS) FROM USED_GOODS_BOARD BOARD )
ORDER BY F.FILE_ID DESC