-- 코드를 입력하세요
SELECT H.HISTORY_ID, ROUND((DATEDIFF(H.END_DATE,H.START_DATE)+1) *
        (CASE
            WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 7 THEN 1
            WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 30 THEN 0.95
            WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 90 THEN 0.92
            ELSE 0.85
         END) * C.DAILY_FEE, 0) AS FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID=H.CAR_ID
    WHERE C.CAR_TYPE='트럭'
    ORDER BY FEE DESC, H.HISTORY_ID DESC