-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P, DOCTOR D, APPOINTMENT A
WHERE P.PT_NO = A.PT_NO AND D.MCDP_CD = A.MCDP_CD AND D.DR_ID = A.MDDR_ID
AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
AND DATE_FORMAT(APNT_YMD,'%Y%m%d') = '20220413'
ORDER BY A.APNT_YMD ASC;